#!/usr/bin/env ruby
SASS_EXTENSION = '.css.scss'

RULES = {
  '@color'  => '$color',
  '.border' => '@include border'
}

puts "Usage : ./less2sass file1 file2 ..." if ARGV.empty?

file_names = ARGV
file_names.each do |file_name|
  begin
    text = File.read(file_name)
  rescue Exception => e
    puts "Error : can't open file : #{file_name}"
    next
  end
  RULES.each do |key, value|
    text.gsub!(key, value)
  end
  base_name = File.basename(file_name, 'less')
  File.open(base_name+SASS_EXTENSION, "w") { |file| file << text }
end